import io
import logging
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session

from app.config import settings
from app.database import get_db
from app.models import Material
from app.schemas import CreateFormulaSheet, FormulaSheetOut
from app.services.formula_sheet import generate_formula_sheet

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/formula-sheet", tags=["formula-sheet"])


def _get_material_text(payload: CreateFormulaSheet, db: Session) -> str:
    if payload.material_id is not None:
        mat = db.get(Material, payload.material_id)
        if not mat:
            raise HTTPException(status_code=404, detail="Material not found.")
        base = mat.content
        if payload.syllabus and payload.syllabus.strip():
            return f"{base}\n\nAdditional:\n{payload.syllabus.strip()}"
        return base
    if payload.syllabus and payload.syllabus.strip():
        return payload.syllabus.strip()
    raise HTTPException(status_code=422, detail="Provide material_id or syllabus text.")


@router.post("", response_model=FormulaSheetOut)
def create_formula_sheet(payload: CreateFormulaSheet, db: Session = Depends(get_db)):
    text = _get_material_text(payload, db)
    generated_by, formulas = generate_formula_sheet(
        text,
        provider=payload.provider,
        model_name=payload.model_name,
        language=payload.language,
    )

    # Title from material if available
    title = "Formula Sheet"
    description = f"{len(formulas)} key formulas and concepts"
    if payload.material_id:
        mat = db.get(Material, payload.material_id)
        if mat:
            title = f"{mat.title} — Formula Sheet"
            description = f"Extracted from {mat.title}"

    return FormulaSheetOut(
        title=title,
        description=description,
        formulas=formulas,
        generated_by=generated_by,
        provider=payload.provider,
        model_name=payload.model_name or settings.gemini_model,
        language=payload.language,
    )


@router.post("/pdf")
def download_formula_sheet_pdf(payload: CreateFormulaSheet, db: Session = Depends(get_db)):
    """Generate PDF and return as file download."""
    text = _get_material_text(payload, db)
    generated_by, formulas = generate_formula_sheet(
        text,
        provider=payload.provider,
        model_name=payload.model_name,
        language=payload.language,
    )

    title = "Formula Sheet"
    if payload.material_id:
        mat = db.get(Material, payload.material_id)
        if mat:
            title = f"{mat.title} — Formula Sheet"

    # Try reportlab, fallback to fpdf, fallback to pymupdf text PDF
    pdf_bytes = _build_pdf_bytes(title, formulas, payload.language)

    headers = {"Content-Disposition": f'attachment; filename="formula-sheet.pdf"'}
    return StreamingResponse(io.BytesIO(pdf_bytes), media_type="application/pdf", headers=headers)


def _build_pdf_bytes(title: str, formulas: list[dict], language: str) -> bytes:
    # Try reportlab
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.units import mm
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.enums import TA_LEFT
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        from reportlab.lib import colors

        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=15*mm, bottomMargin=15*mm, leftMargin=15*mm, rightMargin=15*mm)
        styles = getSampleStyleSheet()
        title_style = ParagraphStyle("Title2", parent=styles["Title"], fontSize=18, spaceAfter=6, textColor=colors.HexColor("#111827"))
        heading_style = ParagraphStyle("Heading2", parent=styles["Heading2"], fontSize=12, spaceAfter=4, textColor=colors.HexColor("#1F2937"))
        normal_style = styles["Normal"]
        normal_style.fontSize = 9
        normal_style.leading = 12

        story = []
        story.append(Paragraph(title, title_style))
        story.append(Paragraph(f"Generated by Spidey Tutor • {len(formulas)} formulas • {language}", normal_style))
        story.append(Spacer(1, 8))

        # Group by category
        from collections import defaultdict

        grouped = defaultdict(list)
        for f in formulas:
            grouped[f.get("category", "General")].append(f)

        for cat, items in grouped.items():
            story.append(Paragraph(f"<b>{cat}</b>", heading_style))
            data = [["#", "Formula", "Description"]]
            for idx, it in enumerate(items, 1):
                # Escape for reportlab
                formula = it.get("formula", "").replace("<", "&lt;").replace(">", "&gt;")
                desc = it.get("description", "").replace("<", "&lt;").replace(">", "&gt;")
                title_text = it.get("title", "")
                # Combine title + formula
                formula_para = f"<b>{title_text}</b><br/><font face='Courier' size=9>{formula}</font>"
                data.append([str(idx), Paragraph(formula_para, normal_style), Paragraph(desc, normal_style)])
            t = Table(data, colWidths=[20, 180, 260])
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F3F4F6")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#111827")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("ALIGN", (0, 0), (0, -1), "CENTER"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#D1D5DB")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F9FAFB")]),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]))
            story.append(t)
            story.append(Spacer(1, 10))

        story.append(Paragraph("© Spidey Tutor — Keep revising! You've got this.", normal_style))
        doc.build(story)
        return buf.getvalue()
    except Exception as e:
        logger.warning("reportlab failed (%s), trying fpdf", e)

    # Fallback fpdf2
    try:
        from fpdf import FPDF

        pdf = FPDF(format="A4")
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 16)
        pdf.cell(0, 10, title, ln=True, align="C")
        pdf.set_font("Helvetica", "", 9)
        pdf.cell(0, 6, f"{len(formulas)} formulas • {language}", ln=True, align="C")
        pdf.ln(4)
        for idx, f in enumerate(formulas, 1):
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 6, f"{idx}. {f.get('title','')}  [{f.get('category','')}]", ln=True)
            pdf.set_font("Courier", "", 10)
            pdf.multi_cell(0, 6, f.get("formula",""))
            pdf.set_font("Helvetica", "", 9)
            pdf.multi_cell(0, 5, f.get("description",""))
            pdf.ln(2)
        return pdf.output()
    except Exception as e:
        logger.warning("fpdf failed (%s), falling back to pymupdf", e)

    # Fallback pymupdf simple text PDF
    try:
        import pymupdf

        doc = pymupdf.open()
        page = doc.new_page()
        text = f"{title}\n\n"
        for idx, f in enumerate(formulas, 1):
            text += f"{idx}. {f.get('title')} [{f.get('category')}]\n   {f.get('formula')}\n   {f.get('description')}\n\n"
        page.insert_text((40, 40), text, fontsize=10)
        buf = io.BytesIO()
        doc.save(buf)
        return buf.getvalue()
    except Exception as e:
        logger.exception("All PDF builders failed: %s", e)
        raise HTTPException(status_code=500, detail="PDF generation failed")
